name: LateX to PDF

on:
  push:
    branches: 
      - main
    tags:
       - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: latex2pdf
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.0.3
        with:
          output_dir: output
          main_latex_file: Entrega_1.tex
          ctan_packages: amssymb latexsym amsmath fullpage babel-spanish inputenc
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/Entrega_1.pdf
